# 02 - Advanced Tensor Manipulations in PyTorch

This notebook covers advanced tensor manipulation techniques in PyTorch, such as broadcasting, concatenation, stacking, and splitting. Understanding these operations is crucial for efficient tensor operations and preparing data for deep learning models.

## 1. Broadcasting in PyTorch

Broadcasting is a powerful feature that allows PyTorch to perform operations on tensors of different shapes by automatically expanding them to a compatible shape. This is particularly useful for element-wise operations where the shapes do not initially match.


In [2]:
# Example: Broadcasting in PyTorch
import torch

# Create two tensors of different shapes
a = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
b = torch.tensor([1, 2, 3])              # Shape: (3)

# Broadcasting addition
result = a + b
print('Tensor a:\n', a)
print('Tensor b:', b)
print('Broadcasted Addition Result:\n', result)

Tensor a:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor b: tensor([1, 2, 3])
Broadcasted Addition Result:
 tensor([[2, 4, 6],
        [5, 7, 9]])


## 2. Concatenating Tensors

Concatenation is the process of joining two or more tensors along a specific dimension. In PyTorch, the `torch.cat()` function is used for concatenation. The tensors being concatenated must have the same shape except in the dimension along which they are concatenated.


In [3]:
# Example: Concatenating Tensors
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Concatenate along rows (dim=0)
concat_rows = torch.cat((x, y), dim=0)
print('Concatenated along rows:\n', concat_rows)

# Concatenate along columns (dim=1)
concat_columns = torch.cat((x, y), dim=1)
print('Concatenated along columns:\n', concat_columns)

Concatenated along rows:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Concatenated along columns:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


## 3. Stacking Tensors

Stacking is similar to concatenation, but it creates a new dimension for the tensors being stacked. The `torch.stack()` function is used to stack tensors along a new dimension. The tensors must have the same shape.


In [4]:
# Example: Stacking Tensors
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Stack along a new dimension
stacked = torch.stack((x, y), dim=0)
print('Stacked Tensors along new dimension 0:\n', stacked)

# Stack along a different dimension
stacked_dim1 = torch.stack((x, y), dim=1)
print('Stacked Tensors along new dimension 1:\n', stacked_dim1)

Stacked Tensors along new dimension 0:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Stacked Tensors along new dimension 1:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


## 4. Splitting Tensors

Splitting divides a tensor into a list of tensors along a specified dimension. PyTorch provides functions like `torch.split()` and `torch.chunk()` for splitting tensors.


In [8]:
# Example: Splitting Tensors
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor.shape)

# Split into 3 equal parts along dim=0
split_tensor = torch.split(tensor, split_size_or_sections=1, dim=0)
print('Split Tensors into 3 parts along dim=0:')
for part in split_tensor:
    print(part)

# Chunk into 3 parts along dim=1
chunk_tensor = torch.chunk(tensor, chunks=3, dim=1)
print('\nChunk Tensors into 3 parts along dim=1:')
for part in chunk_tensor:
    print(part)

torch.Size([3, 3])
Split Tensors into 3 parts along dim=0:
tensor([[1, 2, 3]])
tensor([[4, 5, 6]])
tensor([[7, 8, 9]])

Chunk Tensors into 3 parts along dim=1:
tensor([[1],
        [4],
        [7]])
tensor([[2],
        [5],
        [8]])
tensor([[3],
        [6],
        [9]])


## Exercises

1. Create two tensors of shape (2, 3) and perform broadcasting multiplication with a tensor of shape (3).
2. Concatenate three tensors along both rows and columns.
3. Stack multiple tensors along a new dimension and explore the output.
4. Split a tensor into unequal parts and check the resulting shapes.